-- 002_transcripts_and_storage.sql
-- Transcripts table, storage bucket/policies, and least-privilege grants.
-- Storage SQL is guarded so the migration runs in environments without the
-- Supabase Storage schema (e.g. local testcontainers) as well as in Supabase.

-- Transcripts are tenant-scoped metadata for private objects. The actual bytes
-- live in Supabase Storage under an org-scoped path generated by the API.
CREATE TABLE IF NOT EXISTS public.transcripts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id UUID NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
    account_id UUID NOT NULL,
    opportunity_id UUID,
    storage_path TEXT NOT NULL,
    original_filename TEXT NOT NULL,
    size_bytes INTEGER NOT NULL,
    mime_type TEXT NOT NULL,
    uploaded_by UUID NOT NULL REFERENCES public.users(id) ON DELETE RESTRICT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    FOREIGN KEY (account_id, org_id) REFERENCES public.accounts(id, org_id) ON DELETE RESTRICT,
    FOREIGN KEY (opportunity_id, org_id) REFERENCES public.opportunities(id, org_id) ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_transcripts_org_id ON public.transcripts(org_id);
CREATE INDEX IF NOT EXISTS idx_transcripts_account_id ON public.transcripts(account_id, org_id);
CREATE INDEX IF NOT EXISTS idx_transcripts_opportunity_id ON public.transcripts(opportunity_id, org_id);
CREATE INDEX IF NOT EXISTS idx_transcripts_uploaded_by ON public.transcripts(uploaded_by);

-- Least-privilege application grants.
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.transcripts TO app_user;
GRANT REFERENCES ON TABLE public.transcripts TO app_user;
GRANT ALL ON TABLE public.transcripts TO app_admin;

-- Row-level security: membership-bound access to transcripts.
ALTER TABLE public.transcripts ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS org_tenant_transcripts ON public.transcripts;
CREATE POLICY org_tenant_transcripts ON public.transcripts
    FOR ALL TO app_user
    USING (public.is_active_org_member(org_id))
    WITH CHECK (public.is_active_org_member(org_id));

-- Default privileges so future public tables are not automatically reachable by app_user.
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO app_admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO app_admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON FUNCTIONS TO app_admin;

-- Supabase Storage bucket and RLS policies. Skipped entirely when the storage
-- schema is not present (local Postgres without the Storage extension/service).
DO $$
DECLARE
    storage_exists BOOLEAN := EXISTS (SELECT 1 FROM information_schema.schemata WHERE schema_name = 'storage');
BEGIN
    IF NOT storage_exists THEN
        RETURN;
    END IF;

    -- Create the private transcripts bucket if it does not exist.
    -- The id and name are both 'transcripts'; private by default.
    IF NOT EXISTS (SELECT 1 FROM storage.buckets WHERE name = 'transcripts') THEN
        INSERT INTO storage.buckets (id, name, public, owner)
        VALUES ('transcripts', 'transcripts', false, NULL);
    END IF;

    -- The authenticated role (used by the Supabase Storage API) needs access
    -- to the storage schema and objects so RLS policies can be evaluated.
    EXECUTE 'GRANT USAGE ON SCHEMA storage TO authenticated';
    EXECUTE 'GRANT SELECT, INSERT, UPDATE, DELETE ON storage.objects TO authenticated';

    -- Drop any previous policies for this bucket so migrations remain idempotent.
    DROP POLICY IF EXISTS transcripts_select ON storage.objects;
    DROP POLICY IF EXISTS transcripts_insert ON storage.objects;
    DROP POLICY IF EXISTS transcripts_update ON storage.objects;
    DROP POLICY IF EXISTS transcripts_delete ON storage.objects;

    -- Users can only access objects under an org path where they have an active
    -- membership. The first path segment is the org UUID.
    CREATE POLICY transcripts_select ON storage.objects
        FOR SELECT TO authenticated
        USING (
            bucket_id = 'transcripts'
            AND (storage.foldername(name))[1]::uuid IN (
                SELECT m.org_id FROM public.memberships m
                WHERE m.user_id = auth.uid() AND m.active = true
            )
        );

    CREATE POLICY transcripts_insert ON storage.objects
        FOR INSERT TO authenticated
        WITH CHECK (
            bucket_id = 'transcripts'
            AND (storage.foldername(name))[1]::uuid IN (
                SELECT m.org_id FROM public.memberships m
                WHERE m.user_id = auth.uid() AND m.active = true
            )
        );

    CREATE POLICY transcripts_update ON storage.objects
        FOR UPDATE TO authenticated
        USING (
            bucket_id = 'transcripts'
            AND (storage.foldername(name))[1]::uuid IN (
                SELECT m.org_id FROM public.memberships m
                WHERE m.user_id = auth.uid() AND m.active = true
            )
        )
        WITH CHECK (
            bucket_id = 'transcripts'
            AND (storage.foldername(name))[1]::uuid IN (
                SELECT m.org_id FROM public.memberships m
                WHERE m.user_id = auth.uid() AND m.active = true
            )
        );

    CREATE POLICY transcripts_delete ON storage.objects
        FOR DELETE TO authenticated
        USING (
            bucket_id = 'transcripts'
            AND (storage.foldername(name))[1]::uuid IN (
                SELECT m.org_id FROM public.memberships m
                WHERE m.user_id = auth.uid() AND m.active = true
            )
        );
END $$;
