-- 002_transcripts_and_storage.sql
-- Transcripts table, storage bucket/policies, and least-privilege grants.
-- Storage SQL is guarded so the migration runs in environments without the
-- Supabase Storage schema (e.g. local testcontainers) as well as in Supabase.
--
-- Transcripts are tenant-scoped metadata for private objects. The actual bytes
-- live in Supabase Storage under an org-scoped path generated by the API.

-- Unique indexes needed for the composite foreign keys below. Memberships needs
-- a (user_id, org_id) index so transcripts.uploaded_by can reference it, and
-- opportunities needs an (id, account_id, org_id) index so a transcript can
-- reference an opportunity together with its owning account and organization.
CREATE UNIQUE INDEX IF NOT EXISTS idx_memberships_user_org ON public.memberships(user_id, org_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_opportunities_id_account_org ON public.opportunities(id, account_id, org_id);

CREATE TABLE IF NOT EXISTS public.transcripts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id UUID NOT NULL REFERENCES public.organizations(id) ON DELETE RESTRICT,
    account_id UUID NOT NULL,
    opportunity_id UUID,
    storage_path TEXT NOT NULL,
    original_filename TEXT NOT NULL,
    size_bytes INTEGER NOT NULL,
    mime_type TEXT NOT NULL,
    uploaded_by UUID NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    FOREIGN KEY (account_id, org_id) REFERENCES public.accounts(id, org_id) ON DELETE RESTRICT,
    FOREIGN KEY (opportunity_id, account_id, org_id) REFERENCES public.opportunities(id, account_id, org_id) ON DELETE RESTRICT,
    FOREIGN KEY (uploaded_by, org_id) REFERENCES public.memberships(user_id, org_id) ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_transcripts_org_id ON public.transcripts(org_id);
CREATE INDEX IF NOT EXISTS idx_transcripts_account_id ON public.transcripts(account_id, org_id);
CREATE INDEX IF NOT EXISTS idx_transcripts_opportunity_id ON public.transcripts(opportunity_id, org_id);
CREATE INDEX IF NOT EXISTS idx_transcripts_uploaded_by ON public.transcripts(uploaded_by);

-- Row-level security: membership-bound access to transcripts.
ALTER TABLE public.transcripts ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS org_tenant_transcripts ON public.transcripts;
CREATE POLICY org_tenant_transcripts ON public.transcripts
    FOR ALL TO app_user
    USING (public.is_active_org_member(org_id))
    WITH CHECK (public.is_active_org_member(org_id));

-- Least-privilege application grants. Only SELECT/INSERT/DELETE are used by
-- this slice; UPDATE and REFERENCES are not granted.
GRANT SELECT, INSERT, DELETE ON TABLE public.transcripts TO app_user;
GRANT ALL ON TABLE public.transcripts TO app_admin;

-- Default privileges so future public tables are not automatically reachable by app_user.
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO app_admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO app_admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON FUNCTIONS TO app_admin;

-- Dedicated backend Storage role. FastAPI signs a short-lived JWT for this role
-- using a server-side Supabase JWT secret; the browser's authenticated token is
-- never granted direct access to Storage objects.
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_catalog.pg_roles WHERE rolname = 'app_storage') THEN
        CREATE ROLE app_storage NOLOGIN NOBYPASSRLS NOINHERIT;
    ELSE
        ALTER ROLE app_storage NOLOGIN NOBYPASSRLS NOINHERIT;
    END IF;
END $$;

GRANT USAGE ON SCHEMA public TO app_storage;

-- Supabase's authenticator role must be able to switch into app_storage based on
-- the JWT role claim. In production this is the role Supabase Auth uses when a
-- request arrives with `role = "app_storage"` in the JWT.
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_catalog.pg_roles WHERE rolname = 'authenticator') THEN
        EXECUTE 'GRANT app_storage TO authenticator';
    END IF;
END $$;

-- Narrow, app_admin-owned helper for Storage RLS policies. The app_storage role
-- cannot read public.memberships directly, but it can execute this
-- fixed-search-path function to test active membership.
CREATE OR REPLACE FUNCTION public.is_active_org_member_storage(p_user_id UUID, p_org_id UUID)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $func$
    SELECT EXISTS (
        SELECT 1 FROM public.memberships
        WHERE user_id = p_user_id AND org_id = p_org_id AND active = true
    );
$func$;

ALTER FUNCTION public.is_active_org_member_storage(UUID, UUID) OWNER TO app_admin;
REVOKE ALL ON FUNCTION public.is_active_org_member_storage(UUID, UUID) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.is_active_org_member_storage(UUID, UUID) TO app_storage;

-- Supabase Storage bucket and RLS policies. Skipped entirely when the storage
-- schema is not present (local Postgres without the Storage extension/service).
DO $$
DECLARE
    storage_exists BOOLEAN := EXISTS (SELECT 1 FROM information_schema.schemata WHERE schema_name = 'storage');
    auth_exists BOOLEAN := EXISTS (SELECT 1 FROM information_schema.schemata WHERE schema_name = 'auth');
    authenticated_exists BOOLEAN := EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated');
    anon_exists BOOLEAN := EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon');
BEGIN
    IF NOT storage_exists THEN
        RETURN;
    END IF;

    IF NOT auth_exists THEN
        RAISE EXCEPTION 'auth schema is required when storage schema is present';
    END IF;

    -- The transcripts bucket is fixed to this name in code and policies. Create
    -- it private, and force an existing bucket private as well. Fail loudly if
    -- the bucket is or remains public.
    IF EXISTS (SELECT 1 FROM storage.buckets WHERE name = 'transcripts') THEN
        UPDATE storage.buckets SET public = false WHERE name = 'transcripts';
    ELSE
        INSERT INTO storage.buckets (id, name, public, owner)
        VALUES ('transcripts', 'transcripts', false, NULL);
    END IF;

    IF (SELECT public FROM storage.buckets WHERE name = 'transcripts') <> false THEN
        RAISE EXCEPTION 'transcripts bucket must remain private';
    END IF;

    -- Enable RLS on storage.objects so the policies below are actually enforced.
    ALTER TABLE storage.objects ENABLE ROW LEVEL SECURITY;

    -- app_admin needs access to the storage catalog for migrations and tests;
    -- it does not bypass RLS because RLS is enforced on the table itself.
    EXECUTE 'GRANT USAGE ON SCHEMA storage TO app_admin';
    EXECUTE 'GRANT ALL ON ALL TABLES IN SCHEMA storage TO app_admin';

    -- app_storage is the only role that may perform object operations on the
    -- transcripts bucket. The browser's authenticated/anon roles are explicitly
    -- denied direct Storage access.
    EXECUTE 'GRANT USAGE ON SCHEMA storage TO app_storage';
    EXECUTE 'GRANT USAGE ON SCHEMA auth TO app_storage';
    EXECUTE 'GRANT SELECT, INSERT, UPDATE, DELETE ON storage.objects TO app_storage';

    -- auth.uid() is used by the RLS policy below to identify the JWT user.
    IF EXISTS (SELECT 1 FROM pg_proc p JOIN pg_namespace n ON p.pronamespace = n.oid WHERE n.nspname = 'auth' AND p.proname = 'uid') THEN
        EXECUTE 'GRANT EXECUTE ON FUNCTION auth.uid() TO app_storage';
    END IF;

    EXECUTE 'REVOKE ALL ON ALL TABLES IN SCHEMA storage FROM PUBLIC';
    IF authenticated_exists THEN
        EXECUTE 'REVOKE ALL ON ALL TABLES IN SCHEMA storage FROM authenticated';
        EXECUTE 'REVOKE USAGE ON SCHEMA storage FROM authenticated';
    END IF;
    IF anon_exists THEN
        EXECUTE 'REVOKE ALL ON ALL TABLES IN SCHEMA storage FROM anon';
        EXECUTE 'REVOKE USAGE ON SCHEMA storage FROM anon';
    END IF;

    -- Drop any previous policies for this bucket so migrations remain idempotent.
    EXECUTE 'DROP POLICY IF EXISTS transcripts_select ON storage.objects';
    EXECUTE 'DROP POLICY IF EXISTS transcripts_insert ON storage.objects';
    EXECUTE 'DROP POLICY IF EXISTS transcripts_update ON storage.objects';
    EXECUTE 'DROP POLICY IF EXISTS transcripts_delete ON storage.objects';

    -- Users can only access objects under an org path where they have an active
    -- membership. The first path segment is the org UUID. These policies apply to
    -- the app_storage role used by the backend-signed Storage JWT.
    EXECUTE 'CREATE POLICY transcripts_select ON storage.objects
        FOR SELECT TO app_storage
        USING (
            bucket_id = ''transcripts''
            AND public.is_active_org_member_storage(auth.uid(), (storage.foldername(name))[1]::uuid)
        )';

    EXECUTE 'CREATE POLICY transcripts_insert ON storage.objects
        FOR INSERT TO app_storage
        WITH CHECK (
            bucket_id = ''transcripts''
            AND public.is_active_org_member_storage(auth.uid(), (storage.foldername(name))[1]::uuid)
        )';

    EXECUTE 'CREATE POLICY transcripts_update ON storage.objects
        FOR UPDATE TO app_storage
        USING (
            bucket_id = ''transcripts''
            AND public.is_active_org_member_storage(auth.uid(), (storage.foldername(name))[1]::uuid)
        )
        WITH CHECK (
            bucket_id = ''transcripts''
            AND public.is_active_org_member_storage(auth.uid(), (storage.foldername(name))[1]::uuid)
        )';

    EXECUTE 'CREATE POLICY transcripts_delete ON storage.objects
        FOR DELETE TO app_storage
        USING (
            bucket_id = ''transcripts''
            AND public.is_active_org_member_storage(auth.uid(), (storage.foldername(name))[1]::uuid)
        )';
END $$;
